Added: missing step config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -40,53 +40,61 @@ jobs:
             - schema.yaml
             - '*.jar'
   release:
-    - checkout
-    - run:
-        name: Cut new release
-        command: |
-          # assemble current and new version numbers
-          OLD_VERSION=$(mvn -q \
-            -Dexec.executable="echo" -Dexec.args='${project.version}' \
-            --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
-          NEW_VERSION="${OLD_VERSION/-SNAPSHOT/}"
-          echo "Releasing $OLD_VERSION as $NEW_VERSION"
+    docker:
+      - image: circleci/openjdk:8-jdk
+    working_directory: ~/repo
+    environment:
+      # Customize the JVM maximum heap limit
+      MAVEN_OPTS: -Xmx3200m
 
-          # ensure dependencies use release versions
-          mvn versions:use-releases
+    steps:
+      - checkout
+      - run:
+          name: Cut new release
+          command: |
+            # assemble current and new version numbers
+            OLD_VERSION=$(mvn -q \
+              -Dexec.executable="echo" -Dexec.args='${project.version}' \
+              --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
+            NEW_VERSION="${OLD_VERSION/-SNAPSHOT/}"
+            echo "Releasing $OLD_VERSION as $NEW_VERSION"
 
-          # write release version to POM
-          mvn versions:set -DnewVersion="$NEW_VERSION"
+            # ensure dependencies use release versions
+            mvn versions:use-releases
 
-          # setup git
-          git config user.name "Release Script"
-          git config user.email "dummy@aurelian.one"
+            # write release version to POM
+            mvn versions:set -DnewVersion="$NEW_VERSION"
 
-          # commit and tag
-          git add pom.xml
-          git commit -m "release: $NEW_VERSION"
-          git tag "$NEW_VERSION"
+            # setup git
+            git config user.name "Release Script"
+            git config user.email "dummy@aurelian.one"
 
-          # land on master and publish
-          git checkout master
-          git merge --no-edit release
-          git push origin master --tags
+            # commit and tag
+            git add pom.xml
+            git commit -m "release: $NEW_VERSION"
+            git tag "$NEW_VERSION"
 
-          # increment minor version number
-          MAJ_VERSION=$(echo "$NEW_VERSION" | cut -d '.' -f 1)
-          MIN_VERSION=$(echo "$NEW_VERSION" | cut -d '.' -f 2)
-          NEW_MINOR=$(($MIN_VERSION + 1))
-          DEV_VERSION="$MAJ_VERSION.$NEW_MINOR-SNAPSHOT"
+            # land on master and publish
+            git checkout master
+            git merge --no-edit release
+            git push origin master --tags
 
-          # ready development branch
-          git checkout develop
-          git merge --no-edit release
-          mvn -s .circleci/settings.xml versions:set -DnewVersion="$DEV_VERSION"
-          git add pom.xml
-          git commit -m "ready for development: $DEV_VERSION"
-          git push origin develop
+            # increment minor version number
+            MAJ_VERSION=$(echo "$NEW_VERSION" | cut -d '.' -f 1)
+            MIN_VERSION=$(echo "$NEW_VERSION" | cut -d '.' -f 2)
+            NEW_MINOR=$(($MIN_VERSION + 1))
+            DEV_VERSION="$MAJ_VERSION.$NEW_MINOR-SNAPSHOT"
 
-          # clean up release branch
-          git push origin :release
+            # ready development branch
+            git checkout develop
+            git merge --no-edit release
+            mvn versions:set -DnewVersion="$DEV_VERSION"
+            git add pom.xml
+            git commit -m "ready for development: $DEV_VERSION"
+            git push origin develop
+
+            # clean up release branch
+            git push origin :release
 
 workflows:
   version: 2
